[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true

[profile.default.optimizer_details]
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config